[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
name = "speedtype-backend"
port = 3001 