name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - 'SpeedType/frontend/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Debug Environment
        run: |
          echo "Current directory:"
          pwd
          echo "\nDirectory contents:"
          ls -la
          echo "\nFrontend directory contents:"
          ls -la SpeedType/frontend || echo "Frontend directory not found"

      - name: Install Dependencies
        working-directory: SpeedType/frontend
        run: |
          echo "Installing dependencies..."
          npm install
        env:
          CI: true

      - name: Build
        working-directory: SpeedType/frontend
        run: npm run build
        env:
          CI: true

      - name: Configure Custom Domain
        working-directory: SpeedType/frontend/dist
        run: |
          echo "speedtype.robocat.ai" > CNAME
          echo "Created CNAME file with content:"
          cat CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: SpeedType/frontend/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Verify Deployment
        run: |
          echo "Verifying deployment..."
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"
          echo "Checking DNS configuration..."
          dig speedtype.robocat.ai +noall +answer || true
          echo "Note: DNS propagation may take up to 24 hours to complete" 