name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'SpeedType/frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd SpeedType/frontend
          npm install

      - name: Create env file
        run: |
          cd SpeedType/frontend
          echo "VITE_NODE_ENV=production" >> .env.production
          echo "VITE_BACKEND_URL=https://speedtype-backend-production.up.railway.app" >> .env.production
          echo "VITE_SOCKET_TIMEOUT=5000" >> .env.production
          echo "VITE_RETRY_DELAY=1000" >> .env.production
          echo "VITE_RECONNECTION_ATTEMPTS=5" >> .env.production
          echo "VITE_SOCKET_TRANSPORTS=[\"websocket\", \"polling\"]" >> .env.production
          echo "VITE_SOCKET_AUTO_CONNECT=true" >> .env.production
          echo "VITE_SOCKET_RECONNECTION=true" >> .env.production

      - name: Build
        run: |
          cd SpeedType/frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./SpeedType/frontend/dist 