name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'SpeedType/frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd SpeedType/frontend
          npm install

      - name: Build
        env:
          VITE_NODE_ENV: production
          VITE_BACKEND_URL: https://speedtype-backend-production.up.railway.app
          VITE_SOCKET_TIMEOUT: 5000
          VITE_RETRY_DELAY: 1000
          VITE_RECONNECTION_ATTEMPTS: 5
          VITE_SOCKET_TRANSPORTS: '["websocket","polling"]'
          VITE_SOCKET_AUTO_CONNECT: true
          VITE_SOCKET_RECONNECTION: true
        run: |
          cd SpeedType/frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./SpeedType/frontend/dist 