name: Deploy to Railway

on:
  push:
    branches: [main]
    paths:
      - 'SpeedType/backend/**'
      - '.github/workflows/railway-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Verify Backend Files
        run: |
          echo "Checking backend directory structure:"
          ls -la SpeedType/backend
          echo "\nChecking package.json:"
          cat SpeedType/backend/package.json

      - name: Install Dependencies
        working-directory: SpeedType/backend
        run: npm install

      - name: Build Backend
        working-directory: SpeedType/backend
        run: |
          echo "Building TypeScript..."
          npm run build
          echo "Verifying build output..."
          ls -la dist/

      - name: Setup and Deploy to Railway
        working-directory: SpeedType/backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          NODE_ENV: production
          PORT: 3001
          ALLOWED_ORIGINS: "https://speedtype.robocat.ai,http://localhost:3000"
          CORS_METHODS: "GET,POST,OPTIONS"
          CORS_CREDENTIALS: "true"
        run: |
          echo "Installing Railway CLI..."
          npm install -g @railway/cli
          
          echo "Setting up Railway environment variables..."
          railway variables set NODE_ENV=production
          railway variables set PORT=3001
          railway variables set ALLOWED_ORIGINS="https://speedtype.robocat.ai,http://localhost:3000"
          railway variables set CORS_METHODS="GET,POST,OPTIONS"
          railway variables set CORS_CREDENTIALS="true"
          
          echo "Starting Railway deployment..."
          railway up --service speedtype-backend || exit 1
          
          echo "Deployment initiated, waiting for service to be ready..."
          sleep 30
          
      - name: Verify Deployment
        run: |
          echo "Verifying deployment..."
          for i in {1..3}; do
            echo "Attempt $i to verify deployment..."
            curl -v https://speedtype-backend-production.up.railway.app/api/ || true
            sleep 10
          done 